### ISSUE TITLE
Create the bare-bones architecture diagram

### ISSUE THREAD

**Issue by rihp** [AskobarNetwork/Askolend#1]
recommending the use [draw.io](https://draw.io)
follow the specs listed in the [white paper](https://askobar-network.com/wp-content/uploads/2020/07/askolend-whitepaper.0.2.0.pdf)

**Comment by rihp** [comment]
## Needed Technology
- Uniswap Oracles
- Proof of Locked Liquidity
- Liquidity Dividend Protocol’s certification of tokens

## Questions:
- Who are the "liquidators"?
- On the ABI `liquidateA[x](address account, address
collateral)`, is the `collateral` argument here an ERC20's contract address?
- The lower the tier of the collateral, the lower the collateralization ratio that it should have?
- How many tiers are available in Askolend? Whitepaper suggests 3 according to the Liquidity Dividends Protocol, and 2 `a` tokens

**Comment by benefacto** [comment]
Updated [link for high level diagram](https://app.gleek.io/diagrams/jFxNynrHiNXi_sVwUtQYJQ), second link for [flow diagram](https://app.gleek.io/diagrams/9-m3bnkpeHByiiUFn7haIQ)

**Comment by carlsbad-sunshine** [comment]
>     * Who are the "liquidators"?
Liquidators are any account which calls the `liquidate` methods on a borrower `account` which is below the collaterilzation limit, in order to liquidate collateral until the account is in compliance.
>     * On the ABI `liquidateA[x](address account, address collateral)`, is the `collateral` argument here an ERC20's contract address?
Yes.
>     * The lower the tier of the collateral, the lower the collateralization ratio that it should have?
No. There are only 2 pool tiers: low risk and high risk. When a borrower has an unfunded liability (so far below the collaterilzation limit that the collateral is worth less than the loan) the difference is first made up from the high risk pool. The low risk pool is untouched until the high risk pool is exhausted.
>     * How many tiers are available in Askolend? Whitepaper suggests 3 according to the Liquidity Dividends Protocol, and 2 `a` tokens
2 tiers: high and low risk.

**Comment by carlsbad-sunshine** [comment]
> 
> 
> Updated [link for high level diagram](https://app.gleek.io/diagrams/Xc2GYwt45k_P0EmUWrmcLA), second link for [flow diagram](https://app.gleek.io/diagrams/9-m3bnkpeHByiiUFn7haIQ)

Diagrams are correct, except there are only 2 lending pools not 3.

**Comment by benefacto** [comment]
Removed extra lending pool from diagrams, updated links and cleaned them up
